"""
FastAPI Integration Example
============================
This file shows how to integrate Modal endpoints into your existing FastAPI backend.
Add these routes to your Routers/segmentation_inpainting.py file.

NOTE: This is an EXAMPLE file. Copy relevant parts to your actual router file.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import requests
import base64
import io
from PIL import Image
from typing import Optional

# Create router
router = APIRouter(prefix="/editing", tags=["editing"])

# ========================================
# CONFIGURATION
# ========================================
# TODO: Replace these with actual Modal URLs after deployment
MODAL_URLS = {
    "qwen_white_to_scene": "https://YOUR-USERNAME--qwen-image-edit-server-white-to-scene-endpoint.modal.run",
    "qwen_fusion": "https://YOUR-USERNAME--qwen-image-edit-server-fusion-endpoint.modal.run",
    "sdxl_inpaint": "https://YOUR-USERNAME--sdxl-inpainting-server-inpaint-endpoint.modal.run",
}

# Timeout for Modal requests (in seconds)
MODAL_TIMEOUT = 120  # 2 minutes


# ========================================
# REQUEST/RESPONSE MODELS
# ========================================

class QwenWhiteToSceneRequest(BaseModel):
    """Request model for Qwen white-to-scene editing"""
    image_id: str  # ID of uploaded image in your system
    prompt: str  # Description of desired scene
    negative_prompt: Optional[str] = "blurry, low quality, distorted"
    num_inference_steps: Optional[int] = 30
    guidance_scale: Optional[float] = 7.5
    strength: Optional[float] = 0.8


class QwenFusionRequest(BaseModel):
    """Request model for Qwen fusion editing"""
    image_id: str
    prompt: str
    negative_prompt: Optional[str] = "blurry, low quality, distorted"
    num_inference_steps: Optional[int] = 30
    guidance_scale: Optional[float] = 7.5
    strength: Optional[float] = 0.8


class SDXLInpaintRequest(BaseModel):
    """Request model for SDXL inpainting"""
    image_id: str
    prompt: str
    negative_prompt: Optional[str] = "blurry, low quality, distorted, ugly"
    num_inference_steps: Optional[int] = 40
    guidance_scale: Optional[float] = 7.5
    strength: Optional[float] = 0.99
    lora_name: Optional[str] = None


class EditResponse(BaseModel):
    """Response model for all editing endpoints"""
    success: bool
    image_base64: str
    message: Optional[str] = None
    model_used: str
    lora_used: Optional[str] = None


# ========================================
# HELPER FUNCTIONS
# ========================================

# You'll need to implement these based on your storage system
def get_image_base64(image_id: str) -> str:
    """
    Retrieve image from your storage system and convert to base64.
    
    TODO: Implement this based on your image storage system.
    This might read from:
    - Temporary file storage
    - Database blob field
    - S3/cloud storage
    - In-memory session cache
    
    Returns:
        Base64 encoded image string with data URI prefix
    """
    # Example implementation (replace with your actual storage logic):
    # image_path = f"./temp/{image_id}.png"
    # with Image.open(image_path) as img:
    #     buffer = io.BytesIO()
    #     img.save(buffer, format="PNG")
    #     img_base64 = base64.b64encode(buffer.getvalue()).decode("utf-8")
    #     return f"data:image/png;base64,{img_base64}"
    
    raise NotImplementedError("Implement get_image_base64 based on your storage system")


def get_mask_base64(image_id: str) -> str:
    """
    Retrieve mask for given image ID and convert to base64.
    
    TODO: Implement this based on your mask storage system.
    Masks are generated by MobileSAM in the /apply_mask endpoint.
    
    Returns:
        Base64 encoded mask string with data URI prefix
    """
    # Example implementation:
    # mask_path = f"./temp/{image_id}_mask.png"
    # with Image.open(mask_path) as mask:
    #     buffer = io.BytesIO()
    #     mask.save(buffer, format="PNG")
    #     mask_base64 = base64.b64encode(buffer.getvalue()).decode("utf-8")
    #     return f"data:image/png;base64,{mask_base64}"
    
    raise NotImplementedError("Implement get_mask_base64 based on your storage system")


def call_modal_endpoint(url: str, payload: dict) -> dict:
    """
    Helper function to call Modal endpoints with error handling.
    
    Args:
        url: Modal endpoint URL
        payload: Request payload
    
    Returns:
        Response JSON from Modal
    
    Raises:
        HTTPException if request fails
    """
    try:
        response = requests.post(
            url,
            json=payload,
            timeout=MODAL_TIMEOUT,
        )
        
        if response.status_code != 200:
            raise HTTPException(
                status_code=500,
                detail=f"Modal request failed: {response.status_code} - {response.text}"
            )
        
        return response.json()
    
    except requests.Timeout:
        raise HTTPException(
            status_code=504,
            detail="Modal request timed out. The model might be cold starting (first request takes longer)."
        )
    except requests.RequestException as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to connect to Modal: {str(e)}"
        )


# ========================================
# API ENDPOINTS
# ========================================

@router.post("/qwen_white_to_scene", response_model=EditResponse)
async def qwen_white_to_scene_edit(request: QwenWhiteToSceneRequest):
    """
    Edit image using Qwen's white-to-scene LoRA.
    Converts white backgrounds into realistic scenes.
    
    Example usage:
    ```
    POST /editing/qwen_white_to_scene
    {
        "image_id": "abc123",
        "prompt": "modern office with plants and natural lighting",
        "num_inference_steps": 30
    }
    ```
    """
    try:
        # Get image and mask from storage
        image_base64 = get_image_base64(request.image_id)
        mask_base64 = get_mask_base64(request.image_id)
        
        # Prepare payload for Modal
        payload = {
            "image_base64": image_base64,
            "mask_base64": mask_base64,
            "prompt": request.prompt,
            "negative_prompt": request.negative_prompt,
            "num_inference_steps": request.num_inference_steps,
            "guidance_scale": request.guidance_scale,
            "strength": request.strength,
        }
        
        # Call Modal endpoint
        result = call_modal_endpoint(MODAL_URLS["qwen_white_to_scene"], payload)
        
        # Return response
        return EditResponse(
            success=result.get("success", True),
            image_base64=result["image_base64"],
            model_used="qwen",
            lora_used="white_to_scene",
            message="Successfully edited image with Qwen white-to-scene"
        )
    
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Editing failed: {str(e)}")


@router.post("/qwen_fusion", response_model=EditResponse)
async def qwen_fusion_edit(request: QwenFusionRequest):
    """
    Edit image using Qwen's fusion LoRA.
    Seamlessly blends new elements into existing scenes.
    
    Example usage:
    ```
    POST /editing/qwen_fusion
    {
        "image_id": "abc123",
        "prompt": "add magical glowing aura",
        "num_inference_steps": 30
    }
    ```
    """
    try:
        # Get image and mask from storage
        image_base64 = get_image_base64(request.image_id)
        mask_base64 = get_mask_base64(request.image_id)
        
        # Prepare payload for Modal
        payload = {
            "image_base64": image_base64,
            "mask_base64": mask_base64,
            "prompt": request.prompt,
            "negative_prompt": request.negative_prompt,
            "num_inference_steps": request.num_inference_steps,
            "guidance_scale": request.guidance_scale,
            "strength": request.strength,
        }
        
        # Call Modal endpoint
        result = call_modal_endpoint(MODAL_URLS["qwen_fusion"], payload)
        
        # Return response
        return EditResponse(
            success=result.get("success", True),
            image_base64=result["image_base64"],
            model_used="qwen",
            lora_used="fusion",
            message="Successfully edited image with Qwen fusion"
        )
    
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Editing failed: {str(e)}")


@router.post("/sdxl_inpaint", response_model=EditResponse)
async def sdxl_inpaint_edit(request: SDXLInpaintRequest):
    """
    Edit image using SDXL inpainting.
    High-quality mask-based inpainting with optional LoRA support.
    
    Example usage:
    ```
    POST /editing/sdxl_inpaint
    {
        "image_id": "abc123",
        "prompt": "fluffy white puppy",
        "num_inference_steps": 40,
        "lora_name": "realistic"  // optional
    }
    ```
    """
    try:
        # Get image and mask from storage
        image_base64 = get_image_base64(request.image_id)
        mask_base64 = get_mask_base64(request.image_id)
        
        # Prepare payload for Modal
        payload = {
            "image_base64": image_base64,
            "mask_base64": mask_base64,
            "prompt": request.prompt,
            "negative_prompt": request.negative_prompt,
            "num_inference_steps": request.num_inference_steps,
            "guidance_scale": request.guidance_scale,
            "strength": request.strength,
        }
        
        if request.lora_name:
            payload["lora_name"] = request.lora_name
        
        # Call Modal endpoint
        result = call_modal_endpoint(MODAL_URLS["sdxl_inpaint"], payload)
        
        # Return response
        return EditResponse(
            success=result.get("success", True),
            image_base64=result["image_base64"],
            model_used="sdxl",
            lora_used=result.get("lora_used"),
            message="Successfully inpainted image with SDXL"
        )
    
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inpainting failed: {str(e)}")


@router.get("/modal_status")
async def check_modal_status():
    """
    Check if Modal services are accessible.
    Useful for health checks and debugging.
    
    Returns status of all Modal endpoints.
    """
    status = {}
    
    # Check each service
    for service_name, url in MODAL_URLS.items():
        # Construct health check URL (assumes /health endpoint exists)
        health_url = url.replace("-endpoint.modal.run", "-health.modal.run")
        
        try:
            response = requests.get(health_url, timeout=5)
            if response.status_code == 200:
                status[service_name] = "healthy"
            else:
                status[service_name] = f"unhealthy (status: {response.status_code})"
        except requests.RequestException as e:
            status[service_name] = f"unreachable ({str(e)})"
    
    return {
        "modal_services": status,
        "all_healthy": all(s == "healthy" for s in status.values())
    }


# ========================================
# INTEGRATION NOTES
# ========================================
"""
STEPS TO INTEGRATE INTO YOUR APP:

1. Deploy Modal servers first:
   - modal deploy modal_qwen_server.py
   - modal deploy modal_sdxl_server.py

2. Update MODAL_URLS above with your actual Modal endpoints

3. Implement the helper functions:
   - get_image_base64(): Load image from your storage
   - get_mask_base64(): Load mask from your storage

4. Add these routes to your existing router:
   - Copy the relevant endpoint functions
   - Or import this entire router

5. Update your main.py to include this router:
   ```python
   from Routers import segmentation_inpainting
   app.include_router(segmentation_inpainting.router)
   ```

6. Test the endpoints:
   - Use test_modal_client.py as reference
   - Or test directly with curl/Postman

7. Update your frontend to call these new endpoints:
   ```javascript
   // Example frontend code
   const response = await fetch('/editing/qwen_white_to_scene', {
     method: 'POST',
     headers: {'Content-Type': 'application/json'},
     body: JSON.stringify({
       image_id: imageId,
       prompt: "modern office background"
     })
   });
   const result = await response.json();
   displayImage(result.image_base64);
   ```

WORKFLOW:
1. User uploads image → /editing/upload_image (existing)
2. User clicks on object → /editing/apply_mask (existing, uses MobileSAM)
3. User enters prompt → /editing/qwen_white_to_scene (NEW, uses Modal)
4. Display edited image

COST OPTIMIZATION TIPS:
- Cache frequently used results
- Batch multiple requests if possible
- Use appropriate num_inference_steps (lower = faster but lower quality)
- Monitor usage in Modal dashboard
- Set appropriate container_idle_timeout in Modal servers

TROUBLESHOOTING:
- First request might be slow (cold start ~30s)
- Subsequent requests should be fast (~5-10s)
- If timeout occurs, increase MODAL_TIMEOUT
- Check Modal dashboard for logs and errors
- Use /modal_status endpoint to verify connectivity
"""
